### ISSUE TITLE
ImportError: cannot import name 'ScoreCAM'

### ISSUE THREAD

**Issue by mbary** [frgfm/torch-cam#10]
Hello, 

I am trying to use your implementation of Score CAM.
Before implementing it in my model (pre-trained resnet) I wanted to run the basic example provided in the documentation:

```
from torchvision.models import resnet18
from torchcam.cams import ScoreCAM

model = resnet18(pretrained=True).eval()
cam = ScoreCAM(model, 'layer4', 'conv1')
with torch.no_grad(): out = model(input_tensor)
cam(class_idx=100)
```

However I am getting the error mentioned in the title. 

Initially I've installed it via pip, 
I tried uninstalling it and installing via conda. 

However this then "broke" the torchvision package which required re-installing.

**Comment by frgfm** [comment]
Hi there @mbary,

Apologies, it is simply due to the fact that the last release I made was before I implemented ScoreCAM. If you were to install it by cloning the repo, and then `pip install -e . --upgrade` you should be able to run the example!

It's my fault, the documentation happens to be synchronized with the repo master branch, not necessarily with the last release. I was waiting for feedback or new issues before making another release, but it looks like I'll be able to make it soon.

Thanks! 

_PS: I'll close this as soon as release 0.1.1 is out_

**Comment by frgfm** [comment]
Closing this for now as I just made a new [release](https://github.com/frgfm/torch-cam/releases/tag/v0.1.1), feel free to reopen if you encounter the issue again!
