### ISSUE TITLE
Problem about 3D image visualization

### ISSUE THREAD

**Issue by Ljiaqii** [frgfm/torch-cam#128]
### 🚀 Feature

Hi! I'm doing visual display for my program which is a 3D cube. Now I meet a problem. 
When I was debugging the program, I found that the values of the activation map were all 'nan'. 
My cube size is 32 × 32 × 32 （z, y, x）pixel data and the type of 3D cube is. NPY type. How to change the activation map in line 210 ---'activation_map = cam_extractor(out.squeeze(0).argmax().item(), out)' so that the value is not 'nan'? 
I will put the relevant data and weights in the following links-- https://drive.google.com/drive/folders/19xJiUqVDNrqSzcSkNc0wF95WJ58cOsEV?usp=sharing
By the way, In line 214 of the test.py, I want to add 32 × 32 × 32 cubes visualized slice by slice as 32×32. Can you tell me how to operate this step?
Thank you very much and look forward to your reply! Best regards!

### Motivation & pitch

I want to use cam for 3D image visualization, and I have ready-made data, but I meet a problem. When I was debugging the program, I found that the values of the activation map were all 'nan'. My cube size is 32 × 32 × 32 （z, y, x）pixel data and the type of 3D cube is. NPY type. How to change the activation map in line 210 ---'activation_map = cam_extractor(out.squeeze(0).argmax().item(), out)' so that the value is not 'nan'? 
I will put the relevant data and weights in the following links-- https://drive.google.com/drive/folders/19xJiUqVDNrqSzcSkNc0wF95WJ58cOsEV?usp=sharing
Thanks!

**Comment by frgfm** [comment]
Hi @Ljiaqii :wave: 

Thanks for reporting this! However I believe you used the feature proposal issue template rather than the bug template which seems more appropriate in your case :sweat_smile: 

There are a few things at hand here, but I believe you first need to identify why you get NaN values. If your model itself produced the NaN, this is completely out of the scope of this project. If on the contrary, your model is producing correct outputs but only the CAM is NaN, then perhaps it comes from here, so let's investigate!

In order to help you, could you:
- could you short a minimal code snippet to reproduce your error please? (if you used a specific image, please share it)
- if you prefer working with jupyter notebook, sharing a google colab instead of a google drive?
- to debug, it would be nice to have some details about your environment. Would you mind reporting the output of the following command please?

```shell
wget https://raw.githubusercontent.com/frgfm/torch-cam/master/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Cheers :v:

**Comment by Ljiaqii** [comment]
Oh sorry I haven't been replying to you timely!

We've discussed it in discussions, thank you for your help recently! Best regards!
