### ISSUE TITLE
Missing explaination in example

### ISSUE THREAD

**Issue by FredrikM97** [frgfm/torch-cam#42]
The suggested example below have no explaination where scores come from. I also assume that the import of `cam `is missing,

```
from torcham.cams import SmoothGradCAMpp
from torchvision.models import resnet18

img_tensor = torch.rand((1, 3, 224, 224))
model = resnet18(pretrained=True).eval()
# Hook your model before the forward pass
cam_extractor = cam(model)
# By default the last conv layer will be selected
out = model(input_tensor)
# Retrieve the CAM
activation_map = cam_extractor(out.squeeze(0).argmax().item(), scores)
```

**Comment by frgfm** [comment]
Hi @FredrikM97,

Good catch! I just opened a PR that will fix this, let me know if you encounter other issues :ok_hand:

**Comment by FredrikM97** [comment]
@frgfm Thank you very much! I did find something yesterday. I modified SSCAM to support 5D input but during the init of the weights the GPU memory usage shoot up to >18gb.This is on a singel image of size (1,79,95,79). There after I resize the image to (1,79,224,224) and this takes ~30 gb memory which seem unreasonable. I assume there is a memory leak. Either by me or that already existed. When training the model on a batch size of 6 it take ~5gb memory. For SSCAM I use a batch size of 1 and num_samples is 1. Any ideas? Maybe the garbage collector does not free the memory or the become to big?

**Comment by frgfm** [comment]
I see that you opened an issue, but a few things to keep in mind:
- what do you mean by 5D precisely? tensors of higher dimensions are naturally taking orders of magnitudes more RAM
- compared to a tensor of a RGB image (1, 3, 224, 224), your (1, 79, 224, 224) tensor only takes ~26 times more RAM. Since you forward this into a model, you can be sure that it will take a lot of memory.
- you're comparing training with SSCAM, but the paper is not exactly memory or computation-savy. Feel free to read the paper, but I would suggest SmoothGradCAMpp which is much much faster (the gradient will take some RAM but you won't have the multiple forward mechanism)

**Comment by FredrikM97** [comment]
By 5D I mean: (batch, rgb, depth, hight, width). Read the paper but maybe a bit to fast.

In order to reduce the memory usage could one approach be to take one depth at the time (1,1,1,224,224) and merge them afterwards? Wanted to do at least comparison with SSCAM so still working on a solution.

**Comment by frgfm** [comment]
Gotcha, let's move the discussion to the issue #44
