### ISSUE TITLE
The result of ScoreCAM, SSCAM, ISCAM have no heatmap

### ISSUE THREAD

**Issue by wwdok** [frgfm/torch-cam#50]
## 🐛 Bug
I run the cam-example.py with this image url (https://s3.ax1x.com/2021/03/14/60gHte.png) and class-idx 407, but the result shows no heatmap on ScoreCAM, SSCAM, ISCAM :
![image](https://user-images.githubusercontent.com/43233772/111066469-345afa00-84fa-11eb-9cf1-58a88462caf3.png)

## Environment

Please describe your environement so that the bug can be easily reproduced:

 - Torchcam Version (e.g., 0.1.1): 2021/3/14 installed
 - PyTorch Version (e.g., 1.7): 1.7
 - OS (e.g., Linux): Windows
 - How you installed Torchcam (`conda`, `pip`, source): pip
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2, but i use cpu to run the python script
 - GPU models and configuration:  others are default

By the way, i found the result of grad cam is different with the one generate by this [repo](https://github.com/jacobgil/pytorch-grad-cam), its grad-cam result is : 
![cam](https://user-images.githubusercontent.com/43233772/111066658-1641c980-84fb-11eb-9114-26eeac795483.jpg)

**Comment by frgfm** [comment]
Hello there @wwdok :wave: 

Thank you for reporting this!
The issue about the ScoreCAM family was fixed on master in #37, but I haven't made a release on pypi since then! My suggestion is to simply clone the repo and `pip install -e . --upgrade` to use the latest version :ok_hand: 
On my hand, from the master branch, here is the output for a shorter selection of CAMs:
![master_render](https://user-images.githubusercontent.com/26927750/111070978-5e012a80-84d4-11eb-8042-f2c3ff1598e6.png)


Otherwise, if you're not in a hurry, I just want to implement one last paper (LIFT-CAM) before the next release.


Regarding the difference with https://github.com/jacobgil/pytorch-grad-cam, I appreciate the comparison. Here are some details:

1. **Resizing matters for Imagenet pretrained models**: the repo owner does not resize images to 224x224 before passing them to the model. Since we're using models pretrained on imagenet and designed to work with 224x224 images, this is a big difference. Here is how it now renders adding the resizing (almost identical to the one from this repo):

![cam](https://user-images.githubusercontent.com/26927750/111070058-33ad6e00-84d0-11eb-878d-b7ba02a440b2.jpg)

2. **Image backend & preprocessing transformations also matter**: the repo owner used OpenCV for preprocessing, even with the previous step corrected, there is a small difference between the image input tensor from my script and the other repo. I used the exact same transformations and image backend that were used for training these models. Making this final edit, I finally get the exact same input and model output (and thus the CAM using GradCAM).

I hope this helps, let me know if you have any questions!

**Comment by wwdok** [comment]
Perfect, you completely clear up my questions !

**Comment by irazakharchenko** [comment]
hi, 
I have similar issue. I use ScoreCAM for getting heatmaps.
For some images, the code produces the heatmaps, but for others I get a NAN matrix as an output.

Environment:
torchvision==0.10.1+cu111
Python 3.6.9
OS: Linux
Cuda 11.3
torch-cam repo https://github.com/frgfm/torch-cam/commit/c24a85836d19fecc2a00def4c95ad903e225d612.

**Comment by frgfm** [comment]
Hi @irazakharchenko :wave:

For me to help, I would need a bit more information :sweat_smile: Could you share an example image and the code snippet you used to produce the CAM please?

**Comment by frgfm** [comment]
I think this is deriving from the initial issue but first I would say that you don't seem to iterate on the cam_method, so I would definitely avoid recreating the cam_extractor at each iteration. This should speed up the process (only enable / disable the hooks)

Apart from that, nothing jumps to my mind from the code :man_shrugging: How did you check that there were NaNs in `activation_map`?
